spring:
  application:
    name: cinema-master
  profiles:
    active: dev #???????
  servlet:
    multipart:
      enabled: true #??????
      max-file-size: 10MB #?????????10M
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



  datasource:
    url: jdbc:mysql://localhost:3306/cinema?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 #????????
      min-idle: 10 #???????
      max-active: 20 #?????
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #?????????
      stat-view-servlet: #???????????????
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis?????
    database: 0 # Redis?????????0?
    port: 6379 # Redis???????
    password: # Redis?????????????
    timeout: 300ms # ??????????

minio:
  endpoint: http://localhost:9000 #MinIO??????
  bucketName: mall #?????
  accessKey: minioadmin #???key
  secretKey: minioadmin #?????

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增

jwt:
  tokenHeader: Authorization #JWT??????
  secret: cinema-admin-secret #JWT????????
  expiration: 604800 #JWT??????(60*60*24*7)
  tokenHead: 'Bearer '  #JWT???????

redis:
  database: cinema
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24??

secure:
  ignored:
    urls: # 安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss?????????
    accessKeyId: LTAI5t7Wft3Lks972DRLMWqU # ?????????????
    accessKeySecret: Od3g7Jw3LNkSEMlcG5mmZzjIrRdZOb # ????????????oss????????????
    bucketName: hjcsbucket # oss?????
    policy:
      expire: 300 # ?????(S)
    maxSize: 10 # ??????(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # ????????????
    dir:
      prefix: tj/ # ?????????

springfox:
  documentation:
    # 是否启用Swagger扫描代码生成文档
    enabled: true
    open-api:
      # 是否启用Swagger的open-api
      enabled: true
    swagger-ui:
      # 是否启用Swagger的Web UI
      enabled: true

